name: Visualize the codebase
# run on pull request or push to main
on:
  workflow_dispatch:

jobs:
  visualize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: githubocto/repo-visualizer@0.8.2